### PR TITLE
Adding support for ?of

### PR DESCRIPTION
**Pull request by tufty**
Hi.  forth-mode seemed to be missing the `?of … endof` construct, this should add it.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thank you.

This change fails the `CASE` indentation test.  Can you look into that?

**Comment by tufty** [comment]
Ah, bugger, yes.  I'll have a look.

**Comment by tufty** [comment]
That seems to have done the trick.

**Comment by larsbrinkhoff** [comment]
Thanks!  Merged.

**Comment by ellerh** [comment]
I'd like to remove this because `?of` is not a standard word and it seems rarely used. In fact, I have no clue what it's supposed to do. Eventually there should be a convenient way to customize indentation and fontification. Ideally dependent on the search-order.  Until then, users have to hack around things in forth-mode-hook or live with the disadvantages of non-standard words.
Including every non-standard word in the wild is clearly not the way to go.

**Comment by larsbrinkhoff** [comment]
@tufty, do you have any input on this?  Where have you seen `?of` used?

**Comment by tufty** [comment]
Hi guys.

I was under the impression it was ANS, but it seems not.  It’s certainly part of stellaris, which is mostly what I’m using.

As for usage, generally something like this

… CASE
  DUP EVEN ?OF … ENDOF
  … ( default )
ENDCASE

Thinking about it, it’s almost certainly more efficient to encode the case selector outside the case statement itself, especially if there is more than one ?OF, as you lose the extraneous DUP, viz

… DUP EVEN CASE
   TRUE OF … ENDOF
   … ( default )
ENDCASE

with a potential obfuscation of meaning..

Losing support for it isn’t really a  problem WRT fontificaion, but for stuff used in control structures, failure to indent breaks everything horribly.

I dunno, really.  I’m not a forth god...

Simon

**Pull request merged**
