### PR TITLE
Include tab (\t) as delimiter for comments.

### PR DESCRIPTION
**Pull request by ellerh**
* test/tests.el (forth-backslash-comment-font-lock)
(forth-paren-comment-font-lock): New tests.
* forth-mode.el (forth--syntax-propertize): Handle the new test cases.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
`(forth-assert-face "(foo) " 3 nil)` and `  (forth-assert-face "a\\b " 2 nil)` fail in Emacs 23.  Any idea why?

**Comment by ellerh** [comment]
In Emacs23 `(boundp 'syntax-propertize-function) => nil`.  Apparently this was introduced in Emacs24.

**Comment by ellerh** [comment]
I think it would be reasonable to drop support for Emacs23 as 23 is now quite old
Testing with Emacs25 and Emacs24 seems more productive than backporting things to Emacs23.

**Comment by larsbrinkhoff** [comment]
Superceded by #31, I understand?

**Comment by larsbrinkhoff** [comment]
> I think it would be reasonable to drop support for Emacs23 as 23 is now quite old

I agree it's not worth any significant effort to support Emacs 23.  I'd like to keep some minimal support by e.g. reducing functionality or disabling tests.

**Pull request closed without merging**
